project_id = "fjarsnhfbdmlqgyfjzvt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-vercel-app.vercel.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[functions.send-contact-email]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[edge-runtime]
enabled = true
policy = "per_request"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
