import type { Product } from '@/types/product'

export const products: Product[] = [
  {
    id: 'cerave-gel-moussant-236ml',
    name: 'CeraVe Gel Moussant 236ml',
    brand: 'CeraVe',
    price: '9.500 CFA',
    originalPrice: '12.000 CFA',
    image: '/placeholder-gk5yx.png',
    images: [
      '/cerave-foaming-cleanser-front.png',
      '/cerave-foaming-cleanser-back.png',
      '/cerave-foaming-cleanser-ingredients.png',
      '/cerave-foaming-cleanser-texture.png',
    ],
    description:
      'Le gel moussant CeraVe est une double action. Il nettoie et purifie. Ce nettoyant délicat libère de la mousse, les impuretés et le maquillage sans altérer la barrière protectrice de la peau. Sa formule est enrichie.',
    shortDescription: 'Gel nettoyant moussant pour tous types de peau',
    category: 'soin-du-visage',
    subcategory: 'nettoyants',
    inStock: true,
    rating: 4.5,
    reviewCount: 127,
    ingredients: [
      'Aqua/Water',
      'Cocamidopropyl Hydroxysultaine',
      'Sodium Lauroyl Sarcosinate',
      'Niacinamide',
      'Ceramide NP',
      'Ceramide AP',
      'Ceramide EOP',
      'Carbomer',
      'Methylparaben',
      'Sodium Chloride',
      'Sodium Lauroyl Lactylate',
      'Cholesterol',
      'Phenoxyethanol',
      'Disodium EDTA',
      'Dipotassium Phosphate',
      'Sodium Phosphate',
      'Phytosphingosine',
      'Xanthan Gum',
      'Ethylhexylglycerin',
    ],
    usage: [
      'Appliquer sur visage mouillé',
      'Masser délicatement en évitant le contour des yeux',
      "Rincer abondamment à l'eau tiède",
      'Utiliser matin et soir',
      'Suivre avec une crème hydratante',
    ],
    benefits: [
      'Nettoie en profondeur sans dessécher',
      'Préserve la barrière cutanée',
      'Convient aux peaux sensibles',
      'Formule sans parfum',
      'Développé avec des dermatologues',
    ],
    skinType: ['Tous types de peau', 'Peau sensible', 'Peau grasse', 'Peau mixte'],
    tags: ['nettoyant', 'gel', 'moussant', 'ceramides'],
    isOnSale: true,
  },
  {
    id: 'the-ordinary-niacinamide-10-zinc-1',
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    price: '8.500 CFA',
    image: '/the-ordinary-niacinamide.png',
    images: [
      '/placeholder-9culf.png',
      '/the-ordinary-niacinamide-serum-dropper.png',
      '/the-ordinary-niacinamide-serum-texture.png',
    ],
    description:
      "Un sérum concentré à base de niacinamide (vitamine B3) à 10% et de zinc à 1% pour réduire l'apparence des imperfections et réguler la production de sébum.",
    shortDescription: 'Sérum anti-imperfections à la niacinamide',
    category: 'soin-du-visage',
    subcategory: 'serums',
    inStock: true,
    rating: 4.3,
    reviewCount: 89,
    ingredients: [
      'Aqua (Water)',
      'Niacinamide',
      'Pentylene Glycol',
      'Zinc PCA',
      'Dimethyl Isosorbide',
      'Tamarindus Indica Seed Gum',
      'Xanthan Gum',
      'Isoceteth-20',
      'Ethoxydiglycol',
      'Phenoxyethanol',
      'Chlorphenesin',
    ],
    usage: [
      'Appliquer quelques gouttes sur peau propre',
      'Utiliser matin et/ou soir',
      'Éviter le contour des yeux',
      'Suivre avec une crème hydratante',
      'Utiliser une protection solaire le matin',
    ],
    benefits: [
      "Réduit l'apparence des imperfections",
      'Régule la production de sébum',
      'Resserre les pores dilatés',
      'Améliore la texture de la peau',
      'Formule légère et non grasse',
    ],
    skinType: ['Peau grasse', 'Peau mixte', 'Peau à imperfections'],
    tags: ['sérum', 'niacinamide', 'zinc', 'anti-imperfections'],
    isNew: true,
  },
  {
    id: 'nivea-creme-hydratante-corps',
    name: 'NIVEA Crème Hydratante Corps 400ml',
    brand: 'NIVEA',
    price: '6.500 CFA',
    originalPrice: '8.000 CFA',
    image: '/nivea-body-cream-jar.png',
    description:
      "Crème hydratante pour le corps à l'huile d'amande douce, nourrit et protège la peau pendant 48h.",
    shortDescription: 'Crème hydratante corps 48h',
    category: 'corps-bain',
    subcategory: 'hydratants',
    inStock: true,
    rating: 4.2,
    reviewCount: 156,
    skinType: ['Tous types de peau', 'Peau sèche'],
    tags: ['hydratant', 'corps', '48h'],
    isOnSale: true,
  },
  {
    id: 'maybelline-mascara-lash-sensational',
    name: 'Maybelline Mascara Lash Sensational',
    brand: 'Maybelline',
    price: '12.500 CFA',
    image: '/maybelline-pink-mascara.png',
    description:
      'Mascara volumisant et allongeant pour des cils spectaculaires, formule longue tenue.',
    shortDescription: 'Mascara volumisant et allongeant',
    category: 'maquillage',
    subcategory: 'yeux',
    inStock: true,
    rating: 4.4,
    reviewCount: 203,
    tags: ['mascara', 'volume', 'longueur'],
    isNew: false,
  },
  {
    id: 'laneige-water-sleeping-mask',
    name: 'Laneige Water Sleeping Mask 70ml',
    brand: 'Laneige',
    price: '25.000 CFA',
    image: '/laneige-water-mask.png',
    description:
      'Masque de nuit hydratant coréen qui répare et revitalise la peau pendant le sommeil.',
    shortDescription: 'Masque de nuit hydratant coréen',
    category: 'korean-beauty',
    subcategory: 'masques',
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    skinType: ['Tous types de peau', 'Peau déshydratée'],
    tags: ['masque', 'nuit', 'hydratant', 'korean'],
    isNew: true,
  },
  {
    id: 'loreal-shampoo-elvive-extraordinary-oil',
    name: "L'Oréal Elvive Extraordinary Oil Shampoing",
    brand: "L'Oréal",
    price: '7.500 CFA',
    image: '/loreal-elvive-shampoo.png',
    description: 'Shampoing nourrissant aux huiles précieuses pour cheveux secs et abîmés.',
    shortDescription: 'Shampoing nourrissant aux huiles',
    category: 'cheveux',
    subcategory: 'shampoings',
    inStock: true,
    rating: 4.1,
    reviewCount: 134,
    tags: ['shampoing', 'huiles', 'nourrissant'],
  },
  {
    id: 'mustela-gel-lavant-doux',
    name: 'Mustela Gel Lavant Doux 500ml',
    brand: 'Mustela',
    price: '15.500 CFA',
    image: '/placeholder-rd4du.png',
    description: 'Gel lavant doux pour bébé, nettoie en douceur la peau et les cheveux de bébé.',
    shortDescription: 'Gel lavant doux pour bébé',
    category: 'soins-bebe',
    subcategory: 'nettoyants',
    inStock: true,
    rating: 4.8,
    reviewCount: 67,
    tags: ['bébé', 'doux', 'nettoyant'],
  },
  {
    id: 'chanel-chance-eau-tendre',
    name: 'Chanel Chance Eau Tendre EDT 100ml',
    brand: 'Chanel',
    price: '85.000 CFA',
    originalPrice: '95.000 CFA',
    image: '/chanel-chance-pink-bottle.png',
    description: 'Eau de toilette florale et fruitée, une fragrance délicate et raffinée.',
    shortDescription: 'Eau de toilette florale et fruitée',
    category: 'parfums',
    subcategory: 'femme',
    inStock: true,
    rating: 4.6,
    reviewCount: 45,
    tags: ['parfum', 'floral', 'fruité'],
    isOnSale: true,
  },
]

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((product) => product.category === category)
}

export const getRelatedProducts = (productId: string, limit = 4): Product[] => {
  const product = getProductById(productId)
  if (!product) return []

  return products
    .filter((p) => p.id !== productId && p.category === product.category)
    .slice(0, limit)
}
