// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjarsnhfbdmlqgyfjzvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqYXJzbmhmYmRtbHFneWZqenZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzM2OTksImV4cCI6MjA3MTMwOTY5OX0.Hk09T1oz_w8MvCud3Vi22Lfyv7Z8MKlIqGDZVip0nMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});