import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="top" className="antialiased">
        <div className="w-full text-center text-xs py-2 bg-amber-50 text-amber-800 border-b">
          Livraison en moins de 24h à Dakar (hors dimanches/jours fériés)
        </div>
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
